title: Linh Mon
email: nguyenlinh@kaist.ac.kr
description: >- # this means to ignore newlines until "baseurl:"
  You can edit this line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  Website dành cho các bạn đang mong muốn apply học bổng để du học nước ngoài. website hỗ trợ các vấn đề liên quan đến học bổng chính phủ Hàn Quốc,
  học bổng các trường đại học tại Hàn Quốc và offer các khóa mentor program.
baseurl: "/JekyllGks" # the subpath of your site, e.g. /blog
url: "http://linhmon.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  linhmon
facebook_username: LinhMonKGSP
instagram_username: _linh_mon

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
